language: ruby
rvm:
  - 2.6.3
env:
  matrix:
    - DB=postgresql
  before_script:
    - cp config/database.travis.yml config/database.yml
    - psql -c 'create database travis_ci_test;' -U postgres
    - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate --trace
  cache:
    bundler: true
  before_install:
    export TZ=US/Mountain
  install:
    bundle install
  script:
    bundle exec rspec
