language: ruby
rvm:
- 2.6.3
env:
  matrix:
  - DB=postgresql
  - secure: To4TibXrdj0GElWqHbJ1u39XfWmHLejA4uEbDSBtwi6VfSjxAkPUCgfW85Ngow8l0Fid1FGU8B+OCqegH6WFg/+t5I4QKLFHNQhBYU0NHVyOtpCjqMIapS1AQMKXDNmWbXOakG25xWdg+9ukYAE3RK1lRuMUtM8O9/UsC03swZdN2maMHygxqWE2d5hloIjLLD6fTBWB6nruioqN+et6mWEUkYen78mqj+7Ts1bDAVap0QhJFpl5b5lxKRbGUQR6mm059RyKIhA3BO8fJPC2PPpk0DFb+Xf7Sns8lRt9QvAumH9VkRhCwBuTq9JGWlXC17Nq9MuCz5DS+OQjeNgjX0LNkQ/hdLeML1gKd/3QIZLti7XZaEoPAjfZH9DtAwYfypTBSDZqo8CGz9+u15BP+HfjXGG+q/I2yo2ZxCBil2KyQJ1Fa6Ty1FVlXhboyHL4hh0CQf7Tduym/Tlvs866S/x3nmR3uIEZ0MoMNOMPbgP5XcQbJ2LxnzM/sb8rUU7TO9oMmGeOvr/7WEQ1hTntuwQDc5Z0I+87P+3PWKYpSn5nxGoGLy/06Kx+KxJ31jQ8KYOL5Ybg5fvNV/CHP/+DwT6huRnDr28o4urKZWzMTyXl9P0IppA9TDy2NdE7mqjfWy4vtf19wZKClP4jCkx3nCR2SeqcT2jxXuq1+abkx+A=
  - secure: RCzMg5uBtxuJ6tdLmm195AyxD9rQH/7wb85G2EMqEJlkFyZVy2CzY8iOeAsTNtcQh50Dlv9sIFnZ0fGpuI0DBKSyL6SJmEicDPm8PzqTopVBIjUYfbbixyeBHkIINIlqXCm9nHirWaWFgiybXBuFPUxaEIOnwxRcSRdjTlUjPvBPelQeXR2VfpbBajqD82PVLnIUIHusu11nIoYgGFHIW+Iz3mQyiogTPj/7IrRv/Q5F7QIowiAjeUuD3ithYBIwrTCy1blLIV72UfI0qwSEV2COCClSd391K2X4CjU42r5MjWd61mn/7iTA2OoIXC08fhvRGdNs6dEhQxIkidoLAUWtYMPGVHmp+Z0c6xROObPkQFv9GMTCenCmSVpZT/O+XlUb2jSYt4NdH7Xfhc/andGrWZjDvXKt/79GKCDxR+tiOOnWg+96XiRFLrLp/ImP9l15UaooRlzu5oANWdonoRJi6oZVUHtFZEl5g7qOHPkRHy6f1qUxV62pexb/7Ixr2fZxlni8ySiPwLATCJeX1Rvmo5+ZbFLweakZ5tYLr08ld7mdZ1tDOmpJ/SJPtWwdHq2G6Mq7IJu59Lk+Bhs0Zo/VZEDiZkiOOptNylQxbSPBkwyRBmS7NEnthV1dfnyVq6DOfyNuNG9awlG3BdoLueepO0ZKlGfv20HM4v/mRO4=
  - secure: i+QFTmvu3yFCcM9gByNhQ56eS3pymHXpJ71NvxImDLN20E1iGsm0lryYi01d2AaRSC4BhEX46tqOZRo8lNvrRbmuFRrKVUVj+tZeUPSbxUNVFZAjn5uU0LUpGUdJeDna88UzVOcYjSLs736HSeYw3m77UtbIQaQ2roalqSrKASkZ0CVypjqu4ulCnTINItCtK/xG9d/XRh7PiAo6EUBAsTms8w4bGp4f0hPDBPhtS5/thYVPxD8SsPAQqnc8Lz1PQlixva4kfamarph8UrqEL7TOvi4xy6lGWn7Xvu/sBwUGUdZiYyU4fL/Qvn+UEAYVUi+sbDg4T3KMHpH3Q/eYtj3yqVbd9Bl+RQjTtH2w7URUBC7yOoCNpL3K1/zpjM9rzf2I7xhoBYMBxOmauVNUk+PZXFhbCr4Kk5rTEYItrdgvVnm4C3ysA0aYYvfOc0/NeOo6NpTU8CncQdJIwXCUpkcFxjgf2r1jnhopdNuaTHlzj0hUJRKI+7iMyrB3GEbLiDRQgKS02CRcAVC7mCEzMhAX9r4Yntz+xT87J2VtPQJRcQx+ZO5G5RF2ODI+ZqQFIUWsFiq8JGdTeeaPKq3OMxobaTH2No/4EyOW1yRPZzNewReZChl02IaLJo3FnyeGjOJbS6RwIYwKpzKOleliF/nHZGWPy5cR8dy0ByASHlQ=
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- bundle exec rspec
before_install:
- export TZ=US/Mountain
addons:
  postgresql: '9.4'
